set_auto_on_off_enable:
  # Description of the service
  description: Enable or disable auto on/off for a specific day of the week
  # Different fields that your service accepts
  fields:
    day_of_week:
      description: "The day of the week to enable (sun, mon, tue, wed, thu, fri, sat)"
      example: mon
    enable:
      description: "Boolean value indicating whether to enable or disable auto on/off"
      example: "on"

set_auto_on_off_times:
  # Description of the service
  description: Set the auto on and off times for each day of the week
  # Different fields that your service accepts
  fields:
    day_of_week:
      description: "The day of the week to change (sun, mon, tue, wed, thu, fri, sat)"
      example: mon
    hour_on:
      description: The hour to turn the machine on (0..23)
      example: 6
    minute_on:
      description: The minute to turn the machine on (0..59)
      example: 6
    hour_off:
      description: The hour to turn the machine off (0..23)
      example: 5
    minute_off:
      description: The minute to turn the machine off (0..59)
      example: 10

set_dose:
  # Description of the service
  description: Sets the dose for a specific key
  # Different fields that your service accepts
  fields:
    key:
      description: "The key to program (1-5)"
      example: 1
    pulses:
      description: "The dose in pulses (roughly ~0.5ml per pulse)"
      example: 122

set_dose_hot_water:
  # Description of the service
  description: Sets the dose for hot water
  # Different fields that your service accepts
  fields:
    seconds:
      description: "The number of seconds to stream hot water"
      example: 8

set_prebrew_times:
  # Description of the service
  description: Set the prebrewing "on" and "off" times for a specific key
  # Different fields that your service accepts
  fields:
    key:
      description: "The key to program (1-4)"
      example: 1
    seconds_on:
      description: The time in seconds for the pump to run during prebrewing (0-5.9s)
      example: 1.1
    seconds_off:
      description: The time in seconds for the pump to stop during prebrewing (0-5.9s)
      example: 1.1
